// (c) Copyright Mark Miller.
// This source is subject to the Microsoft Public License.
// See http://www.microsoft.com/resources/sharedsource/licensingbasics/sharedsourcelicenses.mspx.
// All other rights reserved.

namespace LinqToStdf.Records.V4
{
    using Attributes;
    ///<summary> Datalog Text Record [50-30] </summary>
    ///<remarks>
    ///     <para>Function:  <br> Contains text information that is to be included in the datalog printout. DTRs may be
    ///                           written under the control of a job plan: for example, to highlight unexpected test
    ///                           results.They may also be generated by the tester executive software: for example, to
    ///                           indicate that the datalog sampling rate has changed.DTRs are placed as comments in
    ///                           the datalog listing.</br></para>
    ///     <para>Frequency: <br> * Optional </br>
    ///                      <br> * A test data file may contain any number of DTRs.</br></para>
    ///     <para>Location:  <br> Anywhere in the data stream after the initial "FAR-(ATRs)-MIR-(RDR)-(SDRs)" sequence.</br></para></remarks>
    [StringFieldLayout(FieldIndex = 0, RecordProperty = "Text", NameInSpec = "TEXT_DAT")]
    public class Dtr : StdfRecord
    {
        public override string FullName => "Datalog Text Record";
        public override RecordType RecordType => new RecordType(50, 30);

        /// <summary>
        ///     <para>ASCII text string </para>
        ///     <para>TEXT_DAT (C*n)</para>
        /// </summary>
        public string? Text { get; set; }
    }
}
